execution:
  - scenario: test_scenario
    concurrency: 6  # Maximum number of users during warm-up phase
    ramp-up: 0s
    hold-for: 6s  # Duration of the warm-up phase
    iterations: 1  # One iteration per URL in the warm-up phase

  - scenario: test_scenario
    concurrency: 60  # Number of users during the main test phase
    ramp-up: 1s
    hold-for: 60s  # Duration of the main test phase
    iterations: 0  # Infinite iterations during the main test phase

scenarios:
  test_scenario:
    requests:
      - url: "http://127.0.0.1:10000/"
      - url: "http://127.0.0.1:10000/ru"
      - url: "http://127.0.0.1:10000/de"
      - url: "http://127.0.0.1:10000/page"
      - url: "http://127.0.0.1:10000/ru/page"
      - url: "http://127.0.0.1:10000/de/page"
    parallel-requests: 6  # Execute all requests simultaneously

modules:
  console:  # Enables console output during the test
    disable: false

reporting:
  - module: final-stats
  - module: json
    filename: results.json  # Output test results in JSON format
